import '@/src/global.css'
import { SnackBarProvider } from '@/src/providers/snackbar-provider'
import NextAuthProvider from '@/src/providers/session-provider'
import { MThemeProvider } from '@/src/providers/theme-provider'
import { Toaster } from '@/src/components/Toast/toaster'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <NextAuthProvider>
          <MThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange
          >
            <main>
              <SnackBarProvider>{children}</SnackBarProvider>
            </main>
            <Toaster />
          </MThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
